name = "ExcelReaders"
uuid = "c04bee98-12a5-510c-87df-2a230cb6e075"
version = "1.1.1-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extras]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Conda = "1 - 1.8.0"
julia = "1.6"
DataValues = "0.4.4"
PyCall = "1.90"

[targets]
test = ["Test", "TestItemRunner"]
